name: Check Nix config

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/install-nix-action@v31
      - name: Check Nix flake logic
        run: nix flake check . --no-build
