name: Check Nix

on: [push]

jobs:
  check-nix:
    uses: mikojs/actions/.github/workflows/check-nix.yml@main
  check-rust:
    uses: mikojs/actions/.github/workflows/check-rust.yml@main
    with:
      folder: ./overlays/custom
